import os
from typing import Annotated, Literal

from dotenv import load_dotenv

# Wildcard import:
# from langchain_core.messages import * imports every public message class
# from that module, such as BaseMessage, HumanMessage, SystemMessage, AIMessage.
#
# Java-ish mental model: similar to import some.package.*;
#
# It works, but explicit imports are usually easier to read, for example:
# from langchain_core.messages import BaseMessage, HumanMessage, SystemMessage, AIMessage
from langchain_core.messages import *
from langchain_core.tools import tool
from langchain_openai import ChatOpenAI
from langgraph.constants import START, END
from langgraph.graph import add_messages, StateGraph
from tavily import TavilyClient
from typing_extensions import TypedDict

# High-level goal for this file.
# You are building a LangGraph workflow where each step updates shared state:
# topic -> search_results -> draft_report -> approval -> final_report -> file.
"""Build a research agent that:

Takes a research topic
Searches the web for information
Drafts a summary report
Pauses for human approval before finalizing
Saves the approved report to a file
"""

# Load environment variables from the .env file.
# Example: OPENAI_API_KEY=...
load_dotenv()

# ChatOpenAI is the LangChain wrapper around an OpenAI chat model.
# This llm object will be used by graph nodes when they need model output.
llm = ChatOpenAI(model="gpt-4")


# ResearchState is the shared state passed between different LangGraph nodes.
# Java-ish mental model: this is like a DTO that every node can read/update.
class ResearchState(TypedDict):
    # messages stores the conversation history.
    #
    # Annotated[list[BaseMessage], add_messages] means:
    # - the real type is list[BaseMessage]
    # - add_messages tells LangGraph to append new messages instead of replacing
    #   the whole list
    messages: Annotated[list[BaseMessage], add_messages]

    # The research topic provided by the user.
    topic: str

    # Raw or summarized web search results collected by a search node.
    search_results: str

    # First version of the report generated by the LLM.
    draft_report: str

    # Human approval flag.
    # A review node can set this to True or False.
    approved: bool

    # Final report text after approval/revision.
    final_report: str


# -- Tools------

# A tool is a normal Python function that LangChain/LangGraph can call.
# The @tool decorator wraps web_search so it can be invoked with
# web_search.invoke(...).
@tool
def web_search(query: str) -> str:
    """Search the web for information on a topic.

    Args:
        query: The search query.
    """
    try:
        # Tavily is the external search API used to get web results.
        # The API key is read from the .env file through os.getenv().
        client = TavilyClient(api_key=os.getenv("TAVILY_API_KEY"))

        # Run the search and ask Tavily for up to 5 results.
        response = client.search(query, max_results=5)
        results = []

        # response is a dictionary. response.get("results", []) safely gets
        # the results list, or an empty list if "results" is missing.
        for item in response.get("results", []):
            results.append(
                f"Title: {item['title']}\n"
                f"URL: {item['url']}\n"
                # Keep only the first 500 characters of content so the prompt
                # does not become too large.
                f"Content: {item['content'][:500]}\n"
            )

        # If results exist, join them with separators. Otherwise return a
        # friendly no-results message.
        return "\n---\n".join(results) if results else "No results found."

    except Exception as e:
        # Return errors as text so the graph can continue instead of crashing.
        return f"Search error: {str(e)}"


# --- Nodes --- all nodes share the same state object ResearchState

def research_node(state: ResearchState) -> dict:
    """Search for information on the topic."""
    # Read the topic from the shared graph state.
    topic = state["topic"]
    print(f"[Research] Searching for this topic: {topic}")

    # Call the web_search tool. Tool objects use .invoke(...) instead of being
    # called like normal functions.
    results = web_search.invoke(topic)
    print(f"[Research] Found results ({len(results)} chars)")
    print(f" Found results ({results}")

    # Update only the search_results field in the graph state.
    return {"search_results": results}


def draft_node(state: ResearchState) -> dict:
    """Draft a research report from the search results."""
    # Pull the earlier state values created by main() and research_node().
    topic = state["topic"]
    search_results = state["search_results"]

    print("[Draft] Writing report...")

    # Ask the LLM to turn search results into a structured research report.
    response = llm.invoke([
        SystemMessage(content=(
            "You are a research analyst. Write a concise research report based on "
            "the provided search results. Include:\n"
            "1. Executive Summary (2-3 sentences)\n"
            "2. Key Findings (bullet points)\n"
            "3. Analysis (1-2 paragraphs)\n"
            "4. Sources (list URLs from the search results)\n\n"
            f"Topic: {topic}\n\n"
            f"Search Results:\n{search_results}"
        )),
        HumanMessage(content=f"Write a research report on: {topic}")
    ])

    draft = response.content
    print(f"[Draft] Report ready ({len(draft)} chars)")

    # Save the report draft into shared state for the review node.
    return {"draft_report": draft}


def review_node(state: ResearchState) -> dict:
    """Present the draft for human review."""
    # Print visual separators around the draft so it is easy to inspect.
    print("\n" + "=" * 60)
    print("DRAFT RESEARCH REPORT")
    print("=" * 60)
    print(state["draft_report"])
    print("=" * 60)

    approval = input("\nApprove this report? (yes/no/revise): ").strip().lower()

    # If approved, route_after_review() will send the graph to finalize.
    if approval == "yes":
        return {"approved": True}

    # If the user asks for revisions, capture feedback as a HumanMessage.
    # Because messages uses add_messages, this message is appended to history.
    elif approval == "revise":
        feedback = input("What should be changed? ")
        return {
            "approved": False,
            "messages": [HumanMessage(content=f"Please revise the report: {feedback}")]
        }

    # Any other input is treated as not approved.
    else:
        return {"approved": False}


def finalize_node(state: ResearchState) -> dict:
    """Save the approved report."""
    # Use the approved draft as the final report content.
    report = state["draft_report"]

    # Convert the topic into a simple filename-safe slug.
    # Example: "AI Agents in Banking" -> "ai-agents-in-banking"
    topic_slug = state["topic"].lower().replace(" ", "-")[:50]
    filename = f"report-{topic_slug}.md"

    # Make sure the reports folder exists.
    os.makedirs("reports", exist_ok=True)

    # Build a path like reports/report-ai-agents.md.
    filepath = os.path.join("reports", filename)

    # Write the final report to disk.
    with open(filepath, "w") as f:
        f.write(report)

    print(f"\n[Finalize] Report saved to {filepath}")

    # final_report stores the saved filepath.
    # messages appends a final AI status message.
    return {
        "final_report": filepath,
        "messages": [AIMessage(content=f"Report approved and saved to {filepath}")]
    }


def revise_node(state: ResearchState) -> dict:
    """Revise the report based on feedback."""
    # Get the latest feedback message. If none exists, use a generic fallback.
    feedback = state["messages"][-1].content if state["messages"] else "Improve the report."

    print("[Revise] Updating report based on feedback...")

    # Ask the LLM to revise the current draft using the human feedback.
    response = llm.invoke([
        SystemMessage(content=(
            "Revise this research report based on the feedback provided.\n\n"
            f"Current Report:\n{state['draft_report']}\n\n"
            f"Feedback: {feedback}"
        )),
        HumanMessage(content="Please revise the report.")
    ])

    # Replace draft_report with the revised version.
    return {"draft_report": response.content}


# --- Routing ---

def route_after_review(state: ResearchState) -> Literal["finalize", "revise"]:
    # This function decides which node should run after review_node.
    # Literal says the return value should be only "finalize" or "revise".
    if state.get("approved", False):
        return "finalize"
    return "revise"


# --- Build Graph ---

# Create a LangGraph workflow using ResearchState as the shared state shape.
workflow = StateGraph(ResearchState)

# Register each node name with the Python function that runs for that node.
workflow.add_node("research", research_node)
workflow.add_node("draft", draft_node)
workflow.add_node("review", review_node)
workflow.add_node("finalize", finalize_node)
workflow.add_node("revise", revise_node)

# Fixed path:
# START -> research -> draft -> review
workflow.add_edge(START, "research")
workflow.add_edge("research", "draft")
workflow.add_edge("draft", "review")

# Conditional path after review:
# if approved=True  -> finalize
# if approved=False -> revise
workflow.add_conditional_edges("review",
                               route_after_review, {
                                   "finalize": "finalize", "revise": "revise"
                               })

# Intended graph idea:
# revise should go back to review after updating the draft.
# finalize should go to END after saving the report.
workflow.add_edge("revise", "review")
workflow.add_edge("finalize", END)

# Compile the graph into an executable agent.
research_agent = workflow.compile()


# --- Main ---

def main():
    # Ask the user for a topic from the command line.
    topic = input("Research topic: ")

    # Start the graph with the initial state.
    # The nodes will fill in search_results, draft_report, approved,
    # and final_report as the graph runs.
    result = research_agent.invoke({
        "messages": [HumanMessage(content=f"Research: {topic}")],
        "topic": topic,
        "search_results": "",
        "draft_report": "",
        "approved": False,
        "final_report": "",
    })

    # Show the final result to the user.
    if result.get("final_report"):
        print(f"\nDone! Report saved to: {result['final_report']}")
    else:
        print("\nReport was not approved.")


# Run main() only when this file is executed directly:
# python research_agent.py
if __name__ == "__main__":
    main()
